# Generated by Django 4.2.7 on 2023-12-01 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TreeKind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("description", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("major", models.IntegerField()),
                ("minor", models.IntegerField()),
                ("valid", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "kind_of_tree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tree.treekind"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TreeNode",
            fields=[
                ("number", models.IntegerField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.CharField(
                        default="<django.db.models.fields.DateTimeField>_<django.db.models.fields.IntegerField>",
                        max_length=35,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=300)),
                ("data_value", models.JSONField()),
                (
                    "comparison",
                    models.CharField(
                        choices=[
                            ("GT", "greater than"),
                            ("ST", "smaller than"),
                            ("EQ", "equal"),
                            ("NE", "not equal"),
                        ],
                        default="GT",
                        max_length=2,
                    ),
                ),
                (
                    "list_comparison",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ALL", "all fields"),
                            ("ONE", "one field"),
                            ("TWO", "two fields"),
                        ],
                        default="ALL",
                        max_length=3,
                    ),
                ),
                ("explanation", models.CharField(max_length=700)),
                ("true_id", models.CharField(max_length=35)),
                ("true_explanation", models.CharField(max_length=700)),
                ("false_id", models.CharField(max_length=35)),
                ("false_explanation", models.CharField(max_length=700)),
                (
                    "data_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.datatype"
                    ),
                ),
                (
                    "false_color",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="false_color",
                        to="tree.color",
                    ),
                ),
                (
                    "false_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="false_origin",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "tree_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tree.version"
                    ),
                ),
                (
                    "true_color",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="true_color",
                        to="tree.color",
                    ),
                ),
                (
                    "true_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="true_origin",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TreeLeaf",
            fields=[
                ("number", models.IntegerField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.CharField(
                        default="<django.db.models.fields.DateTimeField>_<django.db.models.fields.IntegerField>",
                        max_length=35,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("result", models.BooleanField()),
                (
                    "color",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tree.color",
                    ),
                ),
                (
                    "tree_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tree.version"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=50)),
                (
                    "root",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="tree.treenode"
                    ),
                ),
                (
                    "tree_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tree.version"
                    ),
                ),
            ],
        ),
    ]
